### PR TITLE
Native vs Jgit

### LINKED ISSUE #85: Fallback to jgit if git command doesn't exist
Any objections to adding fallback to jgit if `GitCli.verifyGitCommandExists()` fails [here](https://github.com/palantir/gradle-git-version/blob/develop/src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy#L87)?
@iamdanfox @uschi2000

### PR DESCRIPTION
**Pull request by delta003**
Fix #85

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/gradle-git-version](https://github.com/palantir/gradle-git-version), @delta003! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by delta003** [comment]
So tests are passing with jgit. I can walk you through it tmrw and we can decide how to move forward.

File: src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy [hunk 1]
```diff
@@ -79,65 +72,14 @@ class GitVersionPlugin implements Plugin<Project> {
...
-
-    @Memoized
-    private List<String> getLines(String s) {
-        return LINE_SPLITTER.splitToList(s)
-    }
-
-    @Memoized
-    private String abbrevHash(String s) {
-        return s.substring(0, SHA_ABBR_LENGTH)
+        // return new NativeGitDescribe(project.projectDir).describe(prefix)
```
Comment (helenyuyu) [inline src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy]: did you mean to keep this comment?

Comment (delta003) [reply src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy]: It's really scary to break this plugin considering it's used everywhere, and I'm not expert on git/jgit to be sure I've handled all edge cases.
@iamdanfox and I were thinking of some safe approach:
- compute both
- if one returns null, use the other one
- if both commands succeed, check if output is same
- if it's not, raise an exception (so we can fix the jgit implementation)
- eventually drop native one, once we're confident we have the same behaviour

File: src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+        }
+        RevWalk walk = new RevWalk(git.getRepository())
+        RevCommit commit = walk.parseCommit(headObjectId)
+        List<String> revs = new ArrayList<>()
+        while (commit) {
+            revs.add(commit.getName())
+            try {
+                commit = commit.getParent(0)
+            } catch (Throwable ignored) {
+                commit = null
```
Comment (iamdanfox) [inline src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy]: break

**Comment by delta003** [comment]
@iamdanfox `git describe` has defined behaviour when it comes to multiple tags on same commit. I wrote a comparator that does the same. Added some tests to cover that

File: src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy [hunk 3]
```diff
@@ -79,67 +72,28 @@ class GitVersionPlugin implements Plugin<Project> {
...
-                tagRefs.add(parts.get(0))
+        // TODO(mbakovic): Switch to jgit only implementation
+        String nativeGitDescribe = new NativeGitDescribe(project.projectDir).describe(prefix)
+        String jgitDescribe = new JGitDescribe(project.projectDir).describe(prefix)
+        if (nativeGitDescribe == null) {
+            return jgitDescribe
+        } else if (jgitDescribe == null) {
+            return nativeGitDescribe
+        } else {
+            if (nativeGitDescribe != jgitDescribe) {
```
Comment (iamdanfox) [inline src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy]: use `.equals` here to compare strings instead of `!=`

File: src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy [hunk 4]
```diff
@@ -79,67 +72,28 @@ class GitVersionPlugin implements Plugin<Project> {
...
+                throw new IllegalStateException(String.format(
+                        "Inconsistent git describe, native was %s and jgit was %s", nativeGitDescribe, jgitDescribe))
```
Comment (iamdanfox) [inline src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy]: Thoughts on adding "Please report this on `github.com/palantir/gradle-git-version`"

File: src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+    private File directory
+
+    JGitDescribe(File directory) {
+        this.directory = directory
+    }
+
+    @Override
+    String describe(String prefix) {
+        Git git = Git.wrap(new FileRepository(GitCli.getRootGitDir(directory)))
+        if (!GitUtils.isBackCompatible(git)) {
```
Comment (iamdanfox) [inline src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy]: Not a huge fan of the method name here... why not just call this `isRepoEmpty` ? I don't think the log line should mention back compatibility - users don't really care what the old versions did.

File: src/main/groovy/com/palantir/gradle/gitversion/GitDescribe.groovy [hunk 6]
```diff
@@ -0,0 +1,6 @@
+package com.palantir.gradle.gitversion
+
+interface GitDescribe {
+
+    String describe(String prefix)
```
Comment (iamdanfox) [inline src/main/groovy/com/palantir/gradle/gitversion/GitDescribe.groovy]: I think it would be helpful to add some javadoc explaining that this is effectively `git describe --tags --always --first-parent --match=${prefix}*`, and should return null for empty repos.

File: src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy [hunk 7]
```diff
@@ -0,0 +1,101 @@
...
+import org.eclipse.jgit.lib.ObjectId
+import org.eclipse.jgit.lib.PersonIdent
+import org.eclipse.jgit.lib.Ref
+import org.eclipse.jgit.revwalk.RevCommit
+import org.eclipse.jgit.revwalk.RevTag
+import org.eclipse.jgit.revwalk.RevWalk
+import org.slf4j.Logger
+import org.slf4j.LoggerFactory
+
+class JGitDescribe implements GitDescribe {
```
Comment (iamdanfox) [inline src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy]: I think we need to give future readers some javadoc to help them understand why we built this - specifically that shelling out to `git` is a bit unsafe because older versions of git don't support `--first-parent` and jgit doesn't support this natively (https://github.com/palantir/gradle-git-version/issues/46)

File: src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy [hunk 8]
```diff
@@ -0,0 +1,101 @@
...
+        ObjectId headObjectId
+        try {
+            headObjectId = git.getRepository().resolve(Constants.HEAD)
+        } catch (Throwable ignored) {
+            log.debug("HEAD not found")
+            return null
+        }
+
+        try {
+            RevWalk walk = new RevWalk(git.getRepository())
```
Comment (iamdanfox) [inline src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy]: Could we extract these little blocks into methods, e.g. `revList`, `computeTags` ?

File: src/test/groovy/com/palantir/gradle/gitversion/GitVersionPluginTests.groovy [hunk 9]
```diff
@@ -573,11 +574,95 @@ class GitVersionPluginTests extends Specification {
...
+        git.tag().setAnnotated(false).setName('1.0.0').call()
+        git.tag().setAnnotated(false).setName('3.0.0').call()
+
+        when:
+        BuildResult buildResult = with('printVersion').build()
+
+        then:
+        buildResult.output.contains(":printVersion\n1.0.0\n")
+    }
+
```
Comment (iamdanfox) [inline src/test/groovy/com/palantir/gradle/gitversion/GitVersionPluginTests.groovy:658]: Could we add a test where the git tree contains a symlink to another file? Apparently that was historically an incompatibility between real git and jgit

File: src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy (hunk 4 above)
Comment (delta003) [reply src/main/groovy/com/palantir/gradle/gitversion/GitVersionPlugin.groovy]: +1

File: src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy (hunk 5 above)
Comment (delta003) [reply src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy]: Makes sense. Let's not log anything

File: src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy (hunk 7 above)
Comment (delta003) [reply src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy]: Yes. I'll also add comment in GitVersionPlugin.gitDescribe to explain running both native and jgit

File: src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy (hunk 8 above)
Comment (delta003) [reply src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy]: Looks much better

File: src/test/groovy/com/palantir/gradle/gitversion/GitVersionPluginTests.groovy (hunk 9 above)
Comment (delta003) [reply src/test/groovy/com/palantir/gradle/gitversion/GitVersionPluginTests.groovy:658]: turns out there is already a test for that https://github.com/palantir/gradle-git-version/blob/develop/src/test/groovy/com/palantir/gradle/gitversion/GitVersionPluginTests.groovy#L277

File: src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy [hunk 10]
```diff
@@ -0,0 +1,121 @@
...
+        Git git = Git.wrap(new FileRepository(GitCli.getRootGitDir(directory)))
+        if (!GitUtils.isRepoEmpty(git)) {
+            log.debug("Repository is empty")
+            return null
+        }
+
+        RevCommit headCommit
+        try {
+            ObjectId headObjectId = git.getRepository().resolve(Constants.HEAD)
+            RevWalk walk = new RevWalk(git.getRepository())
```
Comment (delta003) [inline src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy]: @iamdanfox there is some groovy weirdness happening here because walk is used in line 47

Comment (iamdanfox) [reply src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy]: Yeah I just noticed that, will revert my commit but I'm kinda horrified the tests are passing

File: src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy [hunk 11]
```diff
@@ -0,0 +1,123 @@
...
+            }
+        }
+        return revs
+    }
+
+    // Maps all commits returned by 'git show-ref --tags -d' to output of 'git describe --tags --exact-match <commit>'
+    private Map<String, String> mapCommitsToTags(Git git, RevWalk walk) {
+        // Maps commit hash to list of all refs pointing to given commit hash.
+        // All keys in this map should be same as commit hashes in 'git show-ref --tags -d'
+        Map<String, List<RefWithTagName>> commitHashToTags = new HashMap<>()
```
Comment (iamdanfox) [inline src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy:90]: It seems a tiny bit unnecessary to build up a whole list of `RefWithTagNames` and then use the comparator to pull out the minimum - in theory we could just do the comparison whenever we get a new tag so that we only ever hold on to one.

Not sure it's worth blocking the PR for this - I think I'd like to convert everything to java before we try to do any more refactoring!

**Review by iamdanfox — APPROVED** [review]
Let's ship an RC and find out!

File: src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy (hunk 10 above)
Comment (delta003) [reply src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy]: There is a huge bug. Tests aren't running correctly :/ Do not merge

File: src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy (hunk 11 above)
Comment (delta003) [reply src/main/groovy/com/palantir/gradle/gitversion/JGitDescribe.groovy:90]: I really want to rewrite this in Java 8... But addressed this in #89
